services:
  - type: web
    name: mepco-erp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 3000
